## Working with Missing Data in Pandas

In [4]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [5]:
data = {'names': ['steve', 'john', 'richard', 'sarah', 'randy', 'micheal', 'julie'],
        'age': [20,22,20,21,24,23,22],
        'gender': ['Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female'],
        'rank': [2,1,4,5,3,7,6]}

In [6]:
ranking_df = DataFrame(data)
ranking_df.iloc[2:5, 1] = np.nan
ranking_df.iloc[3:6, 3] = np.nan
ranking_df.iloc[3,:] = np.nan
ranking_df
#setting specific groups of columns and rows to NaN

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [7]:
ranking_df.isnull()
#printing df with all values null set to true and false otherwise

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [8]:
ranking_df.notnull()
#printing df with all values not null set to true and false otherwise

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [9]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]
#only returning rows where age is missing

     names  age gender  rank
2  richard  NaN   Male   4.0
3      NaN  NaN    NaN   NaN
4    randy  NaN   Male   NaN

In [10]:
#filling a missing value with a single value
ranking_df.fillna(0)

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   0.0    Male   4.0
3        0   0.0       0   0.0
4    randy   0.0    Male   0.0
5  micheal  23.0    Male   0.0
6    julie  22.0  Female   6.0

In [21]:
#fill missing values with value that comes prior to missing value
ranking_df.fillna(method='pad')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [20]:
#fill missing value with next value that is not missing
ranking_df.fillna(method='bfill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [24]:
#fill missing value using linear method which ignores the index and treats the vals as equally spaced
ranking_df.interpolate(method='linear')

TypeError: Cannot interpolate with str dtype

In [22]:
#drop all rows and cols that have missing values
ranking_df.dropna()

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0

In [25]:
#drop all rows and cols that only contains missing values
ranking_df.dropna(how='all')

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [27]:
#drop all cols which contain at least one missing value
ranking_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [28]:
#drop all rows that have at least one missing value
ranking_df.dropna(axis=0)

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0